version: '2'

services:
  verdaccio:
    restart: unless-stopped
    image: verdaccio/verdaccio
    ports:
    - "127.0.0.1:4873:4873"
    volumes:
    - /srv/docker/verdaccio/conf:/verdaccio/conf
    - /srv/docker/verdaccio/storage:/verdaccio/storage
    - /srv/docker/verdaccio/local_storage:/verdaccio/local_storage
